### PR TITLE
Unknown Fragment: 0x2e

### PR DESCRIPTION
**Pull request by bryab**
I just added the boilerplate necessary to make the wld-cli extract tool not crash when encountering the 0x2e fragment.
My guess is that it has something to do with Meshes, as it's inbetween "Mesh Reference" and "Mesh Animated Vertices Reference".

I have only found a single fragment of this type (I added it to the fixtures)

### CODE REVIEW

**Comment by cjab** [comment]
Whoa, yeah this one looks like a monster 😅

**Comment by bryab** [comment]
Did a bit of sleuth work on this frag.  This pattern works in Imhex, but with only one instance of this frag to work with it's hard to say if this is just sheer luck.

```
struct Data1Entry {
	float x,y,z;
};

struct UnknownFrag2e
{
    s32 string_reference;
    u32 flags;
    u32 count1;
    u32 count2;
    u32 count3;
    u32 count4;
    Data1Entry data1[count1*count2];
};

UnknownFrag2e frag @0x00;
```

**Comment by bryab** [comment]
If the above pattern is not sheer luck then it seems that this is some kind of 2D array where count1 and count2 are the dimensions.  count3 and count4 are probably parameters of some kind.

**Comment by bryab** [comment]
Whats a good way to figure out if this fragment is referenced in a different fragment?

**Comment by cjab** [comment]
Hmm, it could be referenced either by string or by index. So you may be able to search for either the name reference (negative number that becomes an offset into the strings data) OR the index of the fragment in the file. It's likely there will be false positives but that _should_ catch any possible reference I think.

**Comment by cjab** [comment]
Also, I just created a docs directory. If you want to drop your imhex patterns in a subdirectory in there that may end up being helpful :D. I still haven't gotten around to getting it working just yet though 😢.

**Pull request merged**
